traces-db:
  download-url: "https://minio-packet.freedesktop.org/mesa-tracie-public/"

traces:
  - path: glmark2/desktop-blur-radius=5:effect=blur:passes=1:separable=true:windows=4.rdc
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: 8867f3a41f180626d0d4b7661ff5c0f4
      - device: gl-virgl
        checksum: 8867f3a41f180626d0d4b7661ff5c0f4
      - device: gl-panfrost-t860
        checksum: 95df5e619a36e88fe408e45567a2d149
      - device: gl-panfrost-t760
        checksum: 30663eac9a4767d26fbf9b6db9712d9f
  - path: glmark2/jellyfish.rdc
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: e0fe979fee129c0ed42a3059d1a4e1c9
      - device: gl-virgl
        checksum: e0fe979fee129c0ed42a3059d1a4e1c9
      - device: gl-panfrost-t860
        checksum: 1d609b089732be5b6e3e78370abcb149
      - device: gl-panfrost-t760
        checksum: f98ef9118eeaba660c15065dac46e580
  - path: glxgears/glxgears.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: 02aca9b4b4ad6fd60331df6e4f87f2cd
      - device: gl-virgl
        checksum: 02aca9b4b4ad6fd60331df6e4f87f2cd
      - device: gl-panfrost-t860
        checksum: 154039d7bebb366258ddfcc2f196286b
  - path: KhronosGroup-Vulkan-Tools/amd/polaris10/vkcube.gfxr
    expectations:
      - device: vk-amd-polaris10
        checksum: 917cbbf4f09dd62ea26d247a1c70c16e
  - path: LunarG-VulkanSamples/amd/polaris10/Hologram:-w:640:-h:480.gfxr
    expectations:
      - device: vk-amd-polaris10
        checksum: cfde36cd7377068a739c30e3fd171d08
  - path: Wicked-Engine/Tests:Cloth_Physics_Test.trace-dxgi
    expectations:
      - device: vk-amd-polaris10
        checksum: 6b6d27df609b8d086cc3335e6d103581
