traces-db:
  download-url: "https://minio-packet.freedesktop.org/mesa-tracie-public/"

traces:
  - path: glmark2/desktop-blur-radius=5:effect=blur:passes=1:separable=true:windows=4.rdc
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: 8867f3a41f180626d0d4b7661ff5c0f4
  - path: glmark2/jellyfish.rdc
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: e0fe979fee129c0ed42a3059d1a4e1c9
  - path: glxgears/glxgears-2.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: f8eba0fec6e3e0af9cb09844bc73bdc8
  - path: 0ad/0ad.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: d76d0f5b5b064bba3e6a2a122c0799cf
  - path: pathfinder/demo.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: e624d76c70cc3c532f4f54439e13659a
  - path: pathfinder/canvas_moire.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: c4ee0eef519f1a32ba24b7b392b31b28
  - path: pathfinder/canvas_text.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: f8c6d9a5c9248821ed9aaa376bef05c3
  - path: gputest/furmark.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: 248ee9534a1f333b479e599646f56f63
  - path: gputest/pixmark-piano.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: 022b43b7fff9e8623dcfcd91e6bbe7aa
  - path: gputest/triangle.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: c8848dec77ee0c55292417f54c0a1a49
  - path: humus/Portals.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: d6eb6aee7a8a1c85d504a498cbf94659
